sudo: required
services:
    - docker

script:
    - docker build -t refish/node .
    - docker images refish/node

before_deploy:
    - docker login -u refish -p Hastings03

deploy:
    provider: script
    script: docker push refish/node
    on:
        branch: master
